export const HOVERED_CLASS_PORT = 'hovered-class-name'
export const START_JOB_TRACKING_MESSAGE = 'start-job-tracking'
export const CANCEL_JOB_TRACKING_MESSAGE = 'cancel-job-tracking'
export const SET_JOB_ELEMENT_CLASS_MESSAGE = 'set-job-element-class'
export const JOB_ELEMENT_CLASS_STORAGE_KEY_PREFIX = 'job-element-class:'
